### ISSUE TITLE
State of the library?

### ISSUE THREAD

**Issue by thvasilo** [DataSketches/sketches-core-cpp#1]
Hello @AlexanderSaydakov and thanks for starting the effort in bringing DataSketches to C++!

I'm wondering what is the state of this library, would you say it's at least in a state where we can use the base quantile sketch in test projects, or is the functionality itself broken?

Regards,
Theodore

**Comment by jmalkin** [comment]
The library has a test implementation of KLL, not the original quantiles. It superficially seems to be ok, but there are a number of internal architectural decisions we haven't yet made. So we won't yet warrant that it's free of bugs or that the API will be stable.

I'm working on HLL in parallel, but that's even less far along.

**Comment by thvasilo** [comment]
Thanks, I'll take it for a spin on a side project and report back with any problems.
