### ISSUE TITLE
Invalid free thrown at program exit.

### ISSUE THREAD

**Issue by thvasilo** [DataSketches/sketches-core-cpp#2]
Hello.

For my use case I'm creating a vector of KLL sketches that I'm populating with update as I iterate through the dataset. Example:

```c++
std::vector<datasketches::kll_sketch<float>> feature_sketches(NUM_FEATURES);

  // Create sketches for the complete data
  for (const auto &data_point : full_data) {
    // Iterate over non-zero values of data vector
    for (Eigen::SparseVector<float>::InnerIterator it(data_point); it; ++it) {
      feature_sketches[it.index()].update(it.value());
    }
  }
```

At program exit when the vector falls out of scope I get a double free error.

I ran the program with valgrind and have attached the output log [here](https://gist.github.com/thvasilo/364ebda5a86aaf3aa0cc53b4e898fb0f).

Any idea for the cause and how to deal with this? Should I be releasing memory manually in the vector at program exit?

**Comment by AlexanderSaydakov** [comment]
Hi!
I am glad that you are eager to try this code even though it is still a draft.
Your example is specific to your application and requires some other libraries, so I could not use it as it is.
I am almost sure that the problem is caused by a missing explicit copy constructor or assignment operator or both. I will add them shortly.

**Comment by AlexanderSaydakov** [comment]
I pushed the change. Please let me know if it fixed your problem. Thanks.

**Comment by thvasilo** [comment]
Yup this fixes the problem, but the commit introduced some variable shadowing leading to compiler errors. I've created a [small PR](https://github.com/DataSketches/sketches-core-cpp/pull/3) to fix this.

**Comment by AlexanderSaydakov** [comment]
I renamed the enum in a separate unrelated commit. I thought that "flags" would be a better name, and it works for me with gcc 8.1.0. It seems that I called the enum "kll_flags" before for a good reason, but forgot about it. I will roll this change back.

**Comment by thvasilo** [comment]
Cool, I'm using 5.4.0 which comes with Ubuntu LTS 16.04, that one throws an error.
