### ISSUE TITLE
Is de-serialized size different from serialized size?

### ISSUE THREAD

**Issue by thvasilo** [DataSketches/sketches-core-cpp#5]
Hello again, I've run into a corner case I think is worth pointing out.

I was trying to serialize a vector of kll sketches into a fixed size buffer backed by a heap-allocated char array. While the serialization works fine, when I try to de-serialize the elements into an array of the same size I run into issues with writing beyond the array length. I calculate the total size of the sketches by calling `get_serialized_size_bytes()` for each item. I know this one does not include one integer as it says in the code. The serialized size of all the sketches (plus a uint64 for vector size) is 9340 bytes.

[Here's an printout](https://gist.github.com/thvasilo/26b67025c079eeb84cf3419485b303b3) of how many bytes are written/read with the buffers.

The error comes from within the `kll_sketch(uint16_t k, uint8_t flags, std::istream& is)` constructor, and specifically `deserialize_items<T>(is, &items_[levels_[0]], num_items);`[link to code](https://github.com/DataSketches/sketches-core-cpp/blob/master/src/kll/kll_sketch.hpp#L507) where my buffer fails with 

> AssertError:read can not have position exceed buffer length: curr_ptr_: 9216 read size: 1024 buffer_size: 9340

Any idea why that line would trigger a write of 1024 bytes, while the sketch itself is 9340-9216=124 bytes? When I used non-fixed size buffers ser/deser works fine.

**Comment by AlexanderSaydakov** [comment]
What are the types of your input and output streams?
Could you give a code example?

**Comment by thvasilo** [comment]
Sure it's a bit convoluted but let me try.

The streams that I'm using come from [rabit](https://github.com/dmlc/rabit), so they aren's std::stream but can be wrapped to be behave as such, link to code is [here](https://github.com/dmlc/rabit/blob/master/include/rabit/internal/io.h). The assertion error is thrown [here](https://github.com/dmlc/rabit/blob/master/include/rabit/internal/io.h#L31) (less verbose here). If I remove the size check the reading completes successfully so I'm not sure if the problem lies in KLL or the stream implementation.

An example of using both fixed and dynamic stream buffers:

```c++
std::vector<datasketches::kll_sketch<float>> kll_sketches;

// [Populate kll_sketches with data...]

std::vector<datasketches::kll_sketch<float>> kll_copy;
size_t total_byte_size = SketchVectorByteSize(kll_sketches);

std::unique_ptr<char[]> push_buffer_cache_fixed(new char[total_byte_size]);
rabit::utils::MemoryFixSizeBuffer mem_buffer_fixed(push_buffer_cache_fixed.get(), total_byte_size);

std::string push_buffer_cache;
rabit::utils::MemoryBufferStream mem_buffer(&push_buffer_cache);

WriteFromVector(mem_buffer, kll_sketches);
WriteFromVector(mem_buffer_fixed, kll_sketches);
std::cout << "Wrote vector" << std::endl;

mem_buffer.Seek(0);
mem_buffer_fixed.Seek(0);
ReadIntoVector(mem_buffer, kll_copy); // This is fine, no error thrown

std::cout << "Serialized total_byte_size: " << total_byte_size << " de-serialized size: " <<
          mem_buffer.Tell() << std::endl; // These are equal!

ReadIntoVector(mem_buffer_fixed, kll_copy); // Error is thrown here, tries to read beyond the buffer length
std::cout << "Read vector" << std::endl;
```

we get the size of the vector using:

```c++
typedef datasketches::kll_sketch<float> FloatSketch;
static size_t SketchVectorByteSize(const std::vector<FloatSketch> &sketch_vector) {
      size_t byte_sum = 0;
      for (auto const & sketch_ : sketch_vector) {
        byte_sum += sketch_.get_serialized_size_bytes();
      }
      return sizeof(uint64_t) + byte_sum;
    }
```

and the read/write functions are:

```c++
    // Write contents of vec into provided stream
    inline static void WriteFromVector(dmlc::Stream &strm, const std::vector<FloatSketch> &vec) {
      dmlc::ostream os(&strm); // dmlc::ostream is an std::stream
      uint64_t sz = static_cast<uint64_t>(vec.size());
      os.write((char*)&sz, sizeof(uint64_t));
      for (int i = 0; i < sz; ++i) {
        vec[i].serialize(os);
      }
    }

    // Read contents of stream into provided vector
    inline static bool ReadIntoVector(dmlc::Stream &strm, std::vector<FloatSketch> &out_vec) {
      dmlc::istream is(&strm);
      uint64_t size;
      if (!is.read((char*)&size, sizeof(uint64_t))) return false;
      out_vec.resize(size);
      for (int i = 0; i < size; ++i) {
        out_vec[i] = *FloatSketch::deserialize(is);
      }
    }
```

**Comment by thvasilo** [comment]
Good catch, sorry for bothering you with this!
